import { images } from '../../constants';

export const BANK_INFO_LIST = [
  { name: '신한', image: images.shinhan },
  { name: '제주', image: images.shinhan },
  { name: '국민', image: images.gukmin },
  { name: '기업', image: images.giup },
  { name: '농협', image: images.nonghyup },
];

// { name: '산업', image: images.},
// { name: '수협', image: images.},
// { name: '신협', image: images.},
// { name: '우리', image: images.},
// { name: '하나', image: images.},
// { name: '한국씨티', image: images.},
// { name: '카카오뱅크', image: images.},
// { name: '케이뱅크', image: images.},
// { name: '토스뱅크', image: images.},
// { name: '경남', image: images.},
// { name: '광주', image: images.},
// { name: '대구', image: images.},
// { name: '부산', image: images.},
// { name: '전북', image: images.},
// { name: '새마을', image: images.},
// { name: '우체국', image: images.},
// { name: '저축은행', image: images.},
// { name: '지역농.축업', image: images.},
// { name: '도이치', image: images.},
// { name: '중국', image: images.},
// { name: '중국건설', image: images.},
// { name: '중국공상', image: images.},
// { name: 'BNP파리바', image: images.},
// { name: 'BOA', image: images.},
// { name: 'HSBC', image: images.},
// { name: 'JP모간', image: images.},
// { name: 'SC', image: images.},
// { name: '산림조합', image: images.},
// { name: '국세', image: images.},
// { name: '지방세', image: images.},
// { name: '국고금', image: images.},

// { name: '신한투자증권', image: images.},
// { name: '교보증권', image: images.},
// { name: '다올투자증권', image: images.},
// { name: '대신증권', image: images.},
// { name: '메리츠증권', image: images.},
// { name: '미래에셋증권', image: images.},
// { name: '부국증권', image: images.},
// { name: '삼성증권', image: images.},
